# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpagegalleryimage1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagegalleryimage1',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage1',
            name='page',
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage1',
        ),
    ]
